name: 'Member Org Status'
author: 'Brett Logan'
description: 'Checks the status of an org member'
inputs:
  body:
    description: The body of the newly created issue
    required: true
    default: ${{ github.event.comment.body }}
  issue_number:
    description: The GitHub issue number
    required: true
    default: ${{ github.event.issue.number }}
  org:
    description: The GitHub org containing the repo
    required: true
    default: ${{ github.repository_owner }}
  repo:
    description: The repo where the GitHub issue exists
    required: true
  token:
    description: GitHub Admin PAT to open issues and comment
    required: true
runs:
  using: node20
  main: dist/index.js
